name: schooler
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

  # State Management
  provider: 4.3.2+2

  # Dependency Injection
  get_it: 5.0.1

  # Database
  cloud_firestore: 0.14.1+3

  # Authentication
  firebase_auth: 0.18.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_core: 0.5.0+1

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/two.jpg
    - assets/logos/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700